### ISSUE TITLE
Crashes on meshes containing degenerates

### ISSUE THREAD

**Issue by reduz** [Thekla/thekla_atlas#10]
I'm integrating Thekla in [Godot Engine](http://github.org/godotengine). When it works, it's great but in most cases it just crashes because it doesn't seem to like the geometry.

Is there still any interest in further developing this library, so I can report issues together with offending geometry, or should I go look for something else?

**Comment by castano** [comment]
Hi Juan, we have used this code in all the meshes of The Witness and we only had problems with a couple of them. The library certainly should not crash, but I think the problem is likely in the input that you are providing. Meshes are expected to be manifold, so you may need to do some cleanup before parameterizing them. Also, I should integrate our latest internal fixes, just in case! Can you point me to your engine code where thekla_atlas is used? I'd be happy to take a look.

**Comment by reduz** [comment]
Thanks for the reply! It seems all the crashes are due to the meshes i used to test contained degenerates. If i remove them beforehand it works fine. I suggest adding this within the library eventually, as it's difficult to tell what's going on when it just crashes.

**Comment by akien-mga** [comment]
> Can you point me to your engine code where thekla_atlas is used?

It's here: https://github.com/godotengine/godot/blob/master/modules/thekla_unwrap/register_types.cpp

With the thekla code from the master branch, with a couple build fixes that we'll PR soon: https://github.com/godotengine/godot/tree/master/thirdparty/thekla_atlas

**Comment by castano** [comment]
Handling non-manifold meshes is out of the scope of this library. Converting a non-manifold mesh into a manifold mesh is hard to do automatically. For example, if you have three triangles sharing an edge, you could remove one of them, but that's not necessarily the solution that a human would choose.

In the Witness we had an exporter that produced meshes that were guaranteed to be manifold. This was done in a crude way: just removing or detaching one of the offending triangles, but it also selected and highlighted the problematic mesh features so that the artists could easily fix it himself, if he was not OK with the automated solution.
